Repository 467Group3A/rimjobs, pull requests merged in 2023-04, with the labels that each got.

#28 Homepage MVP
  components/fetchNavbar.js
  views/index.ejs
  views/index.html
  views/matts.html
  views/template.html
Labels: enhancement, needs CSS/Redesign

#29 Spaghetti Factory
  components/ccauth.js
  components/featured.js
  components/fetchNavbar.js
  components/fetchParts.js
  rimjobs.db
  server.js
  views/cart.html
  views/ccauth.html
  views/credits.html
  views/index.html
  views/viewinventory.html
Labels: enhancement, project-requirement

#32 Cart and Checkout System MVP
  README.md
  components/cart.js
  components/ccauth.js
  components/fetchNavbar.js
  components/fetchParts.js
  config.js
  destroyDB.py
  generateDB.py
  helper.js
  server.js
  views/cart.html
  views/ccauth.html
  views/parts.ejs
  views/viewinventory.html
Labels: project-requirement

#38 ViewInventory & Cart styling
  assets/css/stylesheet.css
  assets/css/stylesheet.css.map
  assets/css/stylesheet.scss
  assets/fonts/Seven Segment.ttf
  assets/img/drydock.png
  views/cart.html
  views/index.html
  views/viewinventory.html
Labels: needs CSS/Redesign

#49 Admin styling and drawer CSS
  assets/css/stylesheet.css
  assets/css/stylesheet.css.map
  assets/css/stylesheet.scss
  assets/img/handle.png
  components/fetchNavbar.js
  components/replenish.js
  generateDB.py
  views/cart.html
  views/ccauth.html
  views/credits.html
  views/employee.html
  views/index.html
  views/login.html
  views/replenish.html
  views/shippingfees.html
  views/viewinventory.html
  views/vieworderdetails.html
  views/vieworders.html
Labels: enhancement, needs CSS/Redesign

#48 Don't pull this yet
  .gitignore
  README.md
  assets/css/stylesheet.css
  components/cart.js
  components/ccauth.js
  components/featured.js
  components/fetchParts.js
  package-lock.json
  package.json
  server.js
  views/cart.html
  views/ccauth.html
  views/index.html
  views/viewinventory.html
Labels: enhancement

#63 Login Management & 404 Page styling & other misc fixes.
  assets/css/stylesheet.css
  assets/css/stylesheet.css.map
  assets/css/stylesheet.scss
  assets/img/error.jpg
  views/404.html
  views/cart.html
  views/credits.html
  views/employee.html
  views/index.html
  views/managelogins.html
Labels: enhancement, needs CSS/Redesign

#69 Find My Order styling.
  components/fetchNavbar.js
  views/findmyorder.html
Labels: needs CSS/Redesign
